# syntax=docker/dockerfile:1.3
FROM docker.io/elasticms/base-php:8.1.15-cli-dev as builder

# include(Args.m4)
# include(Builder.m4)

FROM docker.io/elasticms/base-php:8.1.15-cli as prd

LABEL be.fgov.elasticms.client.environment="prd"

ENV NODE_ENV=production

# include(Args.m4)
# include(Common.m4)

FROM docker.io/elasticms/base-php:8.1.15-cli-dev as dev

LABEL be.fgov.elasticms.client.environment="dev"

ENV NODE_ENV=development

# include(Args.m4)
# include(Common.m4)